### ISSUE TITLE
additional builtins

### ISSUE THREAD

**Issue by dsikes** [skx/evalfilter#163]
I know it is possible for me to add my own functions, but I was wondering if it would be reasonable to include any (or all) of the following as builtins in this package?

- string comparators (and their NOT counterparts):
        - startswith
        - endswith
        - contains
 
- range comparators
        - between (low, high)
        - between_date(start_date, end_date)

The `between_date` may be handled by the `between`, because dates are already converted into epoch timestamps, so this one may be a bit redundant.

Thoughts?

Thanks!

**Comment by skx** [comment]
I think the string-options are already handed via regular expressions .

```
if ( "Steve Kemp" ~= /^Steve/ ) {  print( "Name starts with 'Steve'\n"); }
if ( "Steve Kemp" ~= /Kemp$/ ) {  print( "Name ends with 'Kemp'\n"); }
if ( "Steve Kemp" ~= /e/ ) {  print( "Name contains 'e'\n"); }

if ( "Bob Smith" !~ /^Steve/ ) { print( "Name does not start with 'Steve'\n"); }
if ( "Bob Smith" !~ /Brown$/ ) { print( "Name does not end with 'Brown'\n"); }
if ( "Bob Smith" !~ /x/ ) { print( "Name does not contain 'x'\n"); }
```

So that leaves only the "number stuff".  I'd be happy to add:

* `min(a, b);` - Return the mimimum of the given pair of values.
* `max(a, b);` - Return the bigger of the given pair of values.
* `between(value, a, b);` - Return true if "value" is `>=` a AND <= b`

Does that sound OK?

**Comment by dsikes** [comment]
Yes. That sounds great. Thanks. 👍
